### ISSUE TITLE
Wrong entries for categories

### ISSUE THREAD

**Issue by LucidAPs** [ItemsAdder/DefaultPack#1]
The new default pack has a few mistakes, for example in the iasurvival categories.yml it has the astral bow under iasurvival when it should be under iaalchemy, causing it to not appear in the bow category.
![unknown (1)](https://user-images.githubusercontent.com/42933023/171362109-01114723-077f-4eb8-b0b8-51098917cdbb.png)

Astral Pickaxe has the same issue.
Demoniac Hammer
Demoniac Pickaxe

**Comment by LoneDev6** [comment]
Thanks!
https://github.com/ItemsAdder/DefaultPack/pull/16
