### ISSUE TITLE
Rubies Craft Into "Block of Cassiterite" Instead Of "Block of Ruby"

### ISSUE THREAD

**Issue by YokoYakashi** [ItemsAdder/DefaultPack#13]
Trying to craft a "Block of Ruby" but "Block of Cassiterite" comes up stead. Crafting files exist. No files have been deleted, I followed the directions of first install.
![2022-08-01_14 13 49](https://user-images.githubusercontent.com/110017390/182137674-cae75124-e348-4bc3-9b08-d8514bc8ad3c.png)

**Comment by LoneDev6** [comment]
Thanks, fixed in the upcoming release https://github.com/ItemsAdder/DefaultPack/pull/9
