### ISSUE TITLE
Can use vanilla items to craft items

### ISSUE THREAD

**Issue by ghost** [ItemsAdder/DefaultPack#15]
![image](https://user-images.githubusercontent.com/68630033/186891129-9ec64841-deda-481a-b457-9d1eb3dfd5b8.png)
If the items in the recipe items to the original items, you can directly craft IA items

**Comment by LoneDev6** [comment]
Test with only itemsadder (and its dependencies) installed.
it surely has to do with another plugin causing this problem.

**Comment by LoneDev6** [comment]
please next time report issues on the itemadder github, this is only for misconfiguration of the default pack.
https://github.com/PluginBugs/Issues-ItemsAdder/issues
