### ISSUE TITLE
Importing the image file in default_pack_2.0.8.zip encounters the following problems

### ISSUE THREAD

**Issue by FZDNSZYT** [ItemsAdder/DefaultPack#20]
![image](https://github.com/ItemsAdder/DefaultPack/assets/86947716/d1d084bc-aff5-4fad-b07d-26017b9ebf31)
![image](https://github.com/ItemsAdder/DefaultPack/assets/86947716/a12414f9-7299-4977-822a-875ccc2531c5)

**Comment by FZDNSZYT** [comment]
There is no error message in the console

**Comment by LoneDev6** [comment]
There is something wrong here...
If you literally follow the installation tutorial step by step you won't have any of the shown issues.
https://itemsadder.devs.beer/first-install

Please do it on a clean ItemsAdder folder, do not skip any step and do not install other packs in the meantime.
