### ISSUE TITLE
Include both `DefaultPack` and `OtherPacks` in the same repository

### ISSUE THREAD

**Issue by srnyx** [ItemsAdder/DefaultPack#5]
This way people can just fork one repository when they want to keep upstream.

**Comment by LoneDev6** [comment]
They are separated because I don't want their files to be in the same repository, because they have too different themes.
Sorry I have to reject this idea

**Comment by srnyx** [comment]
> They are separated because I don't want their files to be in the same repository, because they have too different themes. Sorry I have to reject this idea

I don't mean combining all of the files into the same folders. Just at least make 2 folders in one repository, one named `DefaultPack` and another named `OtherPacks`.
